# https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  rspec-test:
    name: Run rspec

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    
    - name: Install dependencies
      run: bundle install
    
    - name: Set up test database
      run: bin/rails db:create db:schema:load
    
    - name: Run linter
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rake
