# https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  rspec-test:
    name: Run rspec

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Set up Ruby gem cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    
    - name: Install Ruby dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install yarn
      run: npm install yarn -g

    - name: Install node.js dependencies
      run: yarn install
    
    - name: Set up test database
      run: bin/rails db:create db:schema:load
    
    - name: Run linter
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rake
